#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    two,                  tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    three,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    four,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//Right motor, open = 135
// Right motor, closed = 205
//Right Motor Launch = 190

//Left Motor, closed = 15
//Left motor, open = 75
//Left motor, launch = 30;

	servo[two] =  -100;
	servo[four] = -100;


	wait1Msec(5000);

}
