#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lawnMower,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Add driving motors
#pragma DebuggerWindows("joystickGame")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

const int MOTOR_SCALAR = -128;
const int THRESHOLD = 10;
bool turnSpinner = false;



void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

void adjustDistanceToSmall()
{

}

void adjustDistancetoMedium()
{

}

void adjustDistancetoLarge()
{

}

void throw()
{
	motor[armMotor] = 100;
	wait1Msec(650);
	motor[armMotor] = -12;
	wait1Msec(1100);
	motor[armMotor] = 0;
}

void forwards()
{
	motor[motorD] = 30;
	wait1Msec(1000);
}

void backwards()
{
	motor[motorD] = -10;
	wait1Msec(500);
}




















task main()
{
	initializeRobot();

//	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		if(turnSpinner == true)
	  {
			motor[lawnMower] = 50;
    }
    else
  {
  	motor[lawnMower] = 0;
  }

		if ((abs(joystick.joy1_x1) > THRESHOLD) || (abs(joystick.joy1_y1) > THRESHOLD))
		{
			motor[leftWheel] =  (((float)joystick.joy1_x1/MOTOR_SCALAR) - ((float)joystick.joy1_y1/MOTOR_SCALAR))*100;
			motor[rightWheel] = (((float)joystick.joy1_x1/MOTOR_SCALAR) + ((float)joystick.joy1_y1/MOTOR_SCALAR))*100;
		}
		else
		{
			motor[leftWheel] = 0;
			motor[rightWheel] = 0;
		}




		if (joy1Btn(0))
		{
			writeDebugStreamLine("Joy Button 0, Throw");
			adjustDistanceToSmall();
			throw();
		}
		 if (joy1Btn(2))
		{
			writeDebugStreamLine("Joy Button 2, Throw");
			adjustDistancetoMedium();
			throw();
		}
		 if (joy1Btn(3))
		{
			writeDebugStreamLine("Joy Button 3, Throw");
			adjustDistancetoLarge();
			throw();
		}
		 if (joy1Btn(7))
		{
			writeDebugStreamLine("Joy Button 7, Backwards");
			backwards();
		}
		 if (joy1Btn(5))
		{
			writeDebugStreamLine("Joy Button 5, forwards");
			forwards();
		}


		if (joy1Btn(1))
   {
   writeDebugStreamLine("Spinner");
 	   turnSpinner = true;
   }

	}

}
